language: python
python:
  - "3.6"

cache:
  pip: true

stages:
  - name: lint
    if: (branch = master) OR (type = pull_request AND head_branch = master)
#  - name: test
#    if: (branch = master) OR (type = pull_request AND head_branch = master)
  - name: deploy
    if: tag IS present

jobs:
  include:

    - stage: lint
      script:
        - pip install -U pylint
        - pylint gym_2048

#    - stage: test
#      script:
#        - pip install .
#        - echo "TODO!"

    - stage: deploy
      script: true
      before_deploy:
        - echo "$TRAVIS_TAG" > VERSION
      deploy:
        provider: pypi
        user: $PYPI_USERNAME
        password: $PYPI_PASSWORD
        skip_cleanup: true
        on:
          tags: true
